/** Author UI acceptance on an immutable R3 release. Real UI/core/API, ordinary wall clock. */
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {defaultR1Content} from '../core/content-r1.ts';
import {createGame as gameR1,createSnapshot as snapshotR1} from '../core/game-core.ts';
import {defaultR2Content} from '../core/content-r2.ts';
import {createGame as gameR2,createSnapshot as snapshotR2} from '../core/game-core-r2.ts';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),releaseId=process.env.BROWSER_RELEASE_ID||'r3-preview-001',releases=resolve(process.env.DEV_RELEASES_DIR||'.preview/releases');
const startedAt=new Date().toISOString(),runStamp=startedAt.replace(/[:.]/g,'-'),output=resolve(process.env.BROWSER_EVIDENCE_DIR||join(root,'evidence/browser-r3-author',runStamp));
await mkdir(output,{recursive:true});const fixture=await readFile(fileURLToPath(import.meta.url),'utf8');await writeFile(join(output,'fixture.mjs.txt'),fixture);
const port=Number(process.env.BROWSER_PORT||4323);const server=spawn(process.execPath,['scripts/dev.mjs'],{cwd:root,env:{...process.env,DEV_PORT:String(port),RELEASE_ID:releaseId,DEV_RELEASES_DIR:releases,DEV_DATABASE_DIR:join(root,'.preview',`author-database-${runStamp}`)},stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',b=>logs+=b);server.stderr.on('data',b=>logs+=b);
const manifest=JSON.parse(await readFile(join(releases,releaseId,'manifest.json'),'utf8'));
const report={releaseId,sourceHash:manifest.sourceHash,manifest,startedAt,fixtureSha256:createHash('sha256').update(fixture).digest('hex'),scope:'Author immutable-release browser checks, UI commands and ordinary wall clock; not independent QA, hardware FPS or human aesthetic acceptance',tests:[],errors:[]};let browser,page;
const check=(name,evidence)=>{report.tests.push({name,status:'PASS',evidence});console.log('PASS '+name)};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const diag=()=>page.evaluate(()=>window.lastThroneDiagnostics());
const wait=async(fn,timeout=30000)=>page.waitForFunction(fn,null,{timeout});
const saved=async()=>wait(()=>window.lastThroneDiagnostics().saveStatus==='server'&&!document.querySelector('[data-action=start-wave]')?.textContent.includes('Записываем'));
const selectHero=async id=>page.locator(`[data-action=select-hero][data-id=${id}]`).click();
async function buyItem(id,slot){await page.locator('.item-shop summary').click();await page.locator(`[data-action=item-preview][data-item=${id}]`).click();await page.locator(`[data-action=item-slot][data-slot="${slot}"]`).click();await page.locator('[data-action=item-confirm]').click();await saved();}
async function build(padId,kind){await page.locator('[data-action=overview]').click();await page.locator('#context-panel details summary').click();await page.locator(`[data-action=select-pad][data-id=${padId}]`).click();await page.locator(`[data-action=preview][data-kind=${kind}]`).click();await page.locator('[data-action=build-confirm]').click();}
async function expedition(hero,kind){await selectHero(hero);await page.locator('.expedition-menu summary').click();await page.locator(`[data-action=expedition-preview][data-kind=${kind}]`).click();await page.locator('[data-action=expedition-confirm]').click();await saved();}
async function waveEnd(){await wait(()=>['preparation','defeat','victory'].includes(window.lastThroneDiagnostics().phase),180000);const d=await diag();assert.equal(d.phase,'preparation');await saved();return diag();}
async function preparationRace(){
 await saved();await selectHero('pudge');await page.locator('.expedition-menu summary').click();await page.locator('[data-action=expedition-preview][data-kind=camp]').click();
 await page.evaluate(()=>{
  const p=window.__checkpointFault={arm:true,held:false,deniedPuts:0,release:null};
  const complete=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete'),put=IDBObjectStore.prototype.put;
  Object.defineProperty(IDBTransaction.prototype,'oncomplete',{...complete,set(callback){let tx=this;complete.set.call(tx,function(event){if(p.arm&&tx.mode==='readwrite'&&tx.objectStoreNames.contains('runs')){p.arm=false;p.held=true;p.release=()=>{p.held=false;callback.call(tx,event)};}else callback.call(tx,event);});}});
  IDBObjectStore.prototype.put=function(value,...rest){if(p.held&&this.name==='runs'&&value?.latestLocalCheckpoint?.heroes?.some(h=>h.expedition)){p.deniedPuts++;throw new DOMException('Bounded fault: pending preparation write denied','QuotaExceededError');}return put.call(this,value,...rest)};
 });
 await page.locator('[data-action=start-wave]').click();await wait(()=>window.__checkpointFault.held);
 const gated=await page.locator('[data-action=expedition-confirm]').isDisabled();
 if(!gated){await page.locator('[data-action=expedition-confirm]').click();await wait(()=>window.__checkpointFault.deniedPuts>0);}
 const beforeRelease=await diag();await page.evaluate(()=>window.__checkpointFault.release());await wait(()=>window.lastThroneDiagnostics().phase==='wave');await page.locator('[data-action=pause]').click();
 const after=await diag(),stored=await page.evaluate(()=>new Promise((resolve,reject)=>{const open=indexedDB.open('last-throne-saves-v2',1);open.onsuccess=()=>{const db=open.result,request=db.transaction('runs').objectStore('runs').get(sessionStorage.getItem('last-throne-selected-record'));request.onsuccess=()=>{resolve(request.result);db.close()};request.onerror=()=>reject(request.error)};open.onerror=()=>reject(open.error)}));
 report.race={gated,beforeRelease,after,storedCheckpoint:stored.latestLocalCheckpoint,fault:await page.evaluate(()=>({held:window.__checkpointFault.held,deniedPuts:window.__checkpointFault.deniedPuts}))};
 await page.screenshot({path:join(output,'preparation-race.png')});
 const absent=!!after.heroes.find(h=>h.id==='pudge').expedition,storedAbsent=!!stored.latestLocalCheckpoint.heroes.find(h=>h.id==='pudge').expedition;
 if(!gated&&absent&&!storedAbsent)throw Error('REPRODUCED: prep expedition accepted during delayed start checkpoint; wave starts with absent hero but persisted checkpoint has no expedition');
 assert.equal(gated,true);assert.equal(absent,false);assert.equal(storedAbsent,false);check('start checkpoint gates prep mutation and battlefield matches durable local checkpoint',report.race);
}
try{
 let ready=false;for(let i=0;i<300;i++){if(server.exitCode!==null)throw Error('Dev server stopped: '+logs);try{if((await fetch(`http://127.0.0.1:${port}/td/api/v1/ready`)).ok){ready=true;break}}catch{}await delay(100)}if(!ready)throw Error('Readiness failed: '+logs);
 const launchArgs=process.env.BROWSER_LAUNCH_ARGS?JSON.parse(process.env.BROWSER_LAUNCH_ARGS).filter(a=>!['--disable-web-security','--allow-running-insecure-content','--autoplay-policy=no-user-gesture-required'].includes(a)):['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader'];
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE_PATH?{executablePath:process.env.BROWSER_EXECUTABLE_PATH}:{}),args:launchArgs});report.browserVersion=browser.version();
 const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('requestfailed',r=>{if((r.isNavigationRequest()||r.method()==='HEAD')&&r.failure()?.errorText==='net::ERR_ABORTED')return;report.errors.push(r.url()+': '+r.failure()?.errorText)});page.on('dialog',d=>d.accept());
 await page.goto(`http://127.0.0.1:${port}/td/`);await page.getByRole('button',{name:'Новая партия',exact:true}).waitFor({timeout:30000});
 await page.locator('[data-action=settings]').click();await page.locator('#quality-setting').selectOption('low');await page.locator('#sound-setting').check();await page.locator('[data-action=settings-save]').click();
 await page.getByRole('button',{name:'Новая партия',exact:true}).click();await wait(()=>window.lastThroneDiagnostics()?.graphics?.ready);let initial=await diag();assert.equal(initial.totalWaves,15);assert.equal(initial.versions.snapshotSchemaVersion,4);assert.equal(initial.heroes.length,5);assert.equal(initial.graphics.webGLVersion,2);assert.equal(initial.audio.contextState,'running');
 check('R3 pinned save4, fifteen waves, fiveheroes, realWebGL2 and audio activated by gesture',initial);
 if(process.env.BROWSER_SCOPE==='preparation_race'){await preparationRace();}else{
 if(process.env.BROWSER_SCOPE!=='archives'){await selectHero('sniper');assert.equal(await page.locator('.item-slot').count(),2);assert.match(await page.locator('.aegis-slot').innerText(),/Aegis.*пусто/);
 await buyItem('sight_gem',0);await buyItem('swift_charm',1);let bought=await diag();assert.deepEqual(bought.heroes.find(h=>h.id==='sniper').items,['sight_gem','swift_charm']);assert.equal(bought.gold,initial.gold-220);check('two actual paid item slots',bought.heroes.find(h=>h.id==='sniper'));
 await page.locator('.item-shop summary').click();await page.locator('[data-action=item-preview][data-item=healing_lantern]').click();await page.locator('[data-action=item-slot][data-slot="0"]').click();assert.deepEqual((await diag()).heroes.find(h=>h.id==='sniper').items,['sight_gem','swift_charm']);assert.match(await page.locator('.item-confirm').innerText(),/Старый предмет будет утрачен/);await page.locator('[data-action=item-cancel]').click();assert.equal((await diag()).gold,bought.gold);check('fullslot replacement preview and cancel preserve items/gold',true);
 await buyItem('healing_lantern',0);assert.deepEqual((await diag()).heroes.find(h=>h.id==='sniper').items,['healing_lantern','swift_charm']);check('explicit paid fullslot replacement',true);
 await build('pad-m1','ballista');await build('pad-n1','magic_tower');await selectHero('pudge');await page.locator('.expedition-menu summary').click();await page.locator('[data-action=expedition-preview][data-kind=camp]').click();assert.match(await page.locator('.expedition-confirm').innerText(),/10 с/);assert.match(await page.locator('.expedition-confirm').innerText(),/160 золота/);assert.equal((await diag()).heroes.find(h=>h.id==='pudge').expedition,null);await page.locator('.expedition-confirm').scrollIntoViewIfNeeded();await page.screenshot({path:join(output,'01-expedition-preview.png')});await page.locator('[data-action=expedition-cancel]').click();assert.equal((await diag()).heroes.find(h=>h.id==='pudge').expedition,null);check('camp explicit duration/reward/absence confirmation and free cancel',true);
 await expedition('pudge','camp');await wait(()=>window.lastThroneDiagnostics().graphics.absentHeroes.some(h=>h.id==='pudge'));let absence=await diag();assert.equal(absence.heroes.filter(h=>h.expedition).length,1);assert.ok(absence.graphics.absentHeroes.some(h=>h.id==='pudge'));assert.equal(await page.locator('[data-action=teleport-mode]').isDisabled(),true);assert.equal(await page.locator('[data-action=ability]').isDisabled(),true);await delay(400);assert.equal((await diag()).heroes.find(h=>h.id==='pudge').expedition.remainingTicks,300);check('one hero genuinely absent; commands disabled; preparation timer frozen',absence);
 await selectHero('shaman');await page.locator('.expedition-menu summary').click();assert.equal(await page.locator('[data-action=expedition-preview]:enabled').count(),0);await page.locator('[data-action=start-wave]').click();await wait(()=>window.lastThroneDiagnostics().simTick>90);await page.locator('[data-action=pause]').click();let paused=await diag();await delay(400);assert.equal((await diag()).simTick,paused.simTick);assert.equal((await diag()).heroes.find(h=>h.id==='pudge').expedition.remainingTicks,paused.heroes.find(h=>h.id==='pudge').expedition.remainingTicks);assert.equal((await diag()).audio.activeVoices,0);check('pause freezes real expedition ticks and clears sound voices',paused.simTick);await page.locator('.modal [data-action=resume]').click();
 await wait(()=>window.lastThroneDiagnostics().eventTotals['effect:expedition_return']>=1,90000);check('camp automatic return and real gold reward',await diag());await waveEnd();
 await build('pad-s1','magic_tower');await build('pad-m2','magic_tower');await expedition('sniper','shop');await page.locator('[data-action=start-wave]').click();await wait(()=>window.lastThroneDiagnostics().pendingRewards.length===1,120000);await page.screenshot({path:join(output,'02-shop-return-retained-reward.png')});let pending=await waveEnd();assert.deepEqual(pending.heroes.find(h=>h.id==='sniper').items,['healing_lantern','swift_charm']);assert.equal(await page.locator('[data-action=start-wave]').isDisabled(),true);check('real shop returns retained choice with fullslots and blocks nextwave',pending.pendingRewards);
 await page.reload();await page.getByRole('button',{name:'Продолжить R3 · волна 3',exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Продолжить R3 · волна 3',exact:true}).click();await wait(()=>window.lastThroneDiagnostics()?.phase==='preparation'&&window.lastThroneDiagnostics()?.graphics?.ready);let restored=await diag();assert.deepEqual(restored.pendingRewards,pending.pendingRewards);assert.deepEqual(restored.heroes.find(h=>h.id==='sniper').items,pending.heroes.find(h=>h.id==='sniper').items);check('pending reward and full inventory survive cloud/local checkpoint reload',restored.pendingRewards);
 await page.locator('[data-action=reward-discard]').click();assert.match(await page.locator('.reward-card').innerText(),/навсегда удалит/);await page.locator('[data-action=reward-discard-cancel]').click();assert.equal((await diag()).pendingRewards.length,1);check('explicit forfeit preview cancellation retains reward',true);
 const rewardGold=restored.gold;await page.locator('[data-action=reward-item][data-item=sight_gem]').click();await page.locator('[data-action=reward-slot][data-slot="0"]').click();assert.deepEqual((await diag()).heroes.find(h=>h.id==='sniper').items,['healing_lantern','swift_charm']);await page.locator('[data-action=reward-confirm]').click();await wait(()=>window.lastThroneDiagnostics().pendingRewards.length===0&&window.lastThroneDiagnostics().saveStatus==='server');let reward=await diag();assert.equal(reward.gold,rewardGold);assert.deepEqual(reward.heroes.find(h=>h.id==='sniper').items,['sight_gem','swift_charm']);check('free reward explicit fullslot replace and nextwave unlock',reward.heroes.find(h=>h.id==='sniper'));
 await expedition('pudge','roshan');await page.locator('[data-action=start-wave]').click();await wait(()=>window.lastThroneDiagnostics().heroes.find(h=>h.id==='pudge').aegisToken,120000);await selectHero('pudge');let roshan=await diag();assert.equal(roshan.heroes.find(h=>h.id==='pudge').expedition,null);assert.deepEqual(roshan.heroes.find(h=>h.id==='pudge').items,[null,null]);check('Roshan returns separate hero-bound Aegis without itemslot consumption',roshan.heroes.find(h=>h.id==='pudge'));await page.screenshot({path:join(output,'03-roshan-aegis.png')});await waveEnd();
 // Unsupported runtime is a visible failure, independent from the saved active game.
 const unsupported=await context.newPage();await unsupported.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=()=>null});await unsupported.goto(`http://127.0.0.1:${port}/td/`);await unsupported.getByRole('button',{name:'Новая партия',exact:true}).click();await unsupported.getByText(/WebGL 2/).waitFor();check('unsupportedWebGL2 visible failure',await unsupported.locator('.error-message').innerText());await unsupported.close();
 }
 // Create old checkpoints through the current API, then let the current menu verify and navigate exact archived clients.
 for(const legacy of [{release:'r1-002',core:'r1-core-1',content:defaultR1Content,snapshot:snapshotR1(gameR1(defaultR1Content,11)),waves:5,heroes:2},{release:'r2-001',core:'r2-core-1',content:defaultR2Content,snapshot:snapshotR2(gameR2(defaultR2Content,12)),waves:10,heroes:5}]){
  await page.goto(`http://127.0.0.1:${port}/td/`);await page.getByRole('button',{name:'Новая партия',exact:true}).waitFor();let old=await page.evaluate(async legacy=>{const headers={'Content-Type':'application/json'};let create=await fetch('/td/api/v1/runs',{method:'POST',headers,body:JSON.stringify({clientRunId:crypto.randomUUID(),seed:legacy.snapshot.seed,clientReleaseId:legacy.release,coreVersion:legacy.core,contentVersion:legacy.content.contentVersion})});if(!create.ok)throw Error(await create.text());let run=await create.json();let save=await fetch('/td/api/v1/runs/'+run.id+'/checkpoint',{method:'PUT',headers,body:JSON.stringify({requestId:crypto.randomUUID(),expectedRevision:run.revision,snapshotSchemaVersion:legacy.snapshot.schemaVersion,snapshot:legacy.snapshot})});if(!save.ok)throw Error(await save.text());return run;},legacy);await page.reload();await page.locator(`[data-action=continue-cloud][data-id="${old.id}"]`).click();await page.waitForURL(`**/td/releases/${legacy.release}/web/index.html?cloud=*`);await wait(()=>window.lastThroneDiagnostics()?.graphics?.ready);let oldRuntime=await diag();assert.match(await page.locator('#wave-stat').innerText(),new RegExp('1 / '+legacy.waves));assert.equal(oldRuntime.releaseId,legacy.release);assert.equal(oldRuntime.heroes.length,legacy.heroes);const restoredPins=await page.evaluate(()=>new Promise((resolve,reject)=>{const open=indexedDB.open('last-throne-saves-v2',1);open.onsuccess=()=>{const db=open.result,request=db.transaction('runs').objectStore('runs').get(sessionStorage.getItem('last-throne-selected-record'));request.onsuccess=()=>{resolve(request.result.pins);db.close()};request.onerror=()=>reject(request.error)};open.onerror=()=>reject(open.error)}));assert.equal(restoredPins.coreVersion,legacy.core);assert.equal(restoredPins.clientReleaseId,legacy.release);check('retained '+legacy.release+' cloud checkpoint opens exact old client/pins',{url:page.url(),runtime:oldRuntime,pins:restoredPins});
  await page.goto(`http://127.0.0.1:${port}/td/`);await page.getByRole('button',{name:`Продолжить ${legacy.waves===5?'R1':'R2'} · волна 1`,exact:true}).click();await page.waitForURL(`**/td/releases/${legacy.release}/web/index.html?resume=*`);await wait(()=>window.lastThroneDiagnostics()?.graphics?.ready);assert.match(await page.locator('#wave-stat').innerText(),new RegExp('1 / '+legacy.waves));assert.equal((await diag()).releaseId,legacy.release);check('retained '+legacy.release+' local checkpoint verifies archive before navigation',page.url());
 }
 }
 report.manifest=JSON.parse(await readFile(join(releases,releaseId,'manifest.json'),'utf8'));report.sourceHash=report.manifest.sourceHash;assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;if(page){report.failureState=await diag().catch(()=>null);report.body=await page.locator('body').innerText().catch(()=>null);await page.screenshot({path:join(output,'failure.png')}).catch(()=>{})}console.error(error);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();await writeFile(join(output,'report-'+report.status.toLowerCase()+'.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(output,'server.log'),logs);await browser?.close();server.kill('SIGTERM');await Promise.race([new Promise(r=>server.once('exit',r)),delay(3000)]);console.log(JSON.stringify({status:report.status,tests:report.tests.length,errors:report.errors,output}));}
