// Independent acceptance: copy this file verbatim into backend test/db/.
// PostgreSQL is mandatory; no skip or MemoryRepository substitute.
import assert from 'node:assert/strict';
import { randomUUID,createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { test } from 'node:test';
import { Client,Pool } from 'pg';
import { migrate,readMigrations } from '../../dist/db/migrate.js';
import { PgRepository } from '../../dist/profile/repository.js';
import { ProfileService } from '../../dist/profile/service.js';
import { hashPassword } from '../../dist/profile/auth.js';
import { RunSimulation } from '../../dist/combat/simulation.js';

const url=process.env.DATABASE_URL;if(!url)throw Error('Independent real DB acceptance requires DATABASE_URL.');
const quote=s=>`"${s.replaceAll('"','""')}"`;
const op=(profile,clientId,type,payload,operationId=randomUUID())=>({operationId,expectedRevision:profile.revision,clientId,type,payload});
const failure=(code)=>e=>e.code===code;
function tool(cmd,args,input,env=process.env){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{env,stdio:['pipe','pipe','pipe']});const out=[],err=[];p.stdout.on('data',x=>out.push(x));p.stderr.on('data',x=>err.push(x));p.on('error',reject);p.on('close',code=>code===0?resolve(Buffer.concat(out)):reject(Error(`Independent backup tool failed exit ${code}: ${Buffer.concat(err).toString().slice(0,160)}`)));p.stdin.end(input);});}
async function dumpRestore(schema,admin){const u=new URL(url),conn=['-h',u.hostname,'-p',u.port||'5432','-U',decodeURIComponent(u.username),'-d',decodeURIComponent(u.pathname.slice(1))];let dump;
 if(process.env.PG_TEST_CONTAINER){const prefix=['exec','-i',process.env.PG_TEST_CONTAINER],inside=['-h','127.0.0.1','-p','5432','-U',decodeURIComponent(u.username),'-d',decodeURIComponent(u.pathname.slice(1))];dump=await tool('docker',[...prefix,'pg_dump',...inside,'-Fc','--schema',schema,'--no-owner']);await admin.query(`DROP SCHEMA ${quote(schema)} CASCADE`);await tool('docker',[...prefix,'pg_restore',...inside,'--no-owner','--exit-on-error'],dump);}
 else {const env={...process.env,PGPASSWORD:decodeURIComponent(u.password)};dump=await tool(process.env.PG_DUMP_BIN||'pg_dump',[...conn,'-Fc','--schema',schema,'--no-owner'],undefined,env);await admin.query(`DROP SCHEMA ${quote(schema)} CASCADE`);await tool(process.env.PG_RESTORE_BIN||'pg_restore',[...conn,'--no-owner','--exit-on-error'],dump,env);}
 assert.ok(dump.length>1000);return dump.length;
}

test('Independent R3/R4 PostgreSQL profile/replay/atomicity/ownership/durability acceptance',async t=>{
 const admin=new Client({connectionString:url});await admin.connect();const schema='foxy_independent_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${quote(schema)}`);
 const pool=new Pool({connectionString:url,options:`-c search_path=${schema},public`,max:6});const repo=new PgRepository(pool);const c=await pool.connect();
 t.after(async()=>{c.release();await pool.end();await admin.query(`DROP SCHEMA IF EXISTS ${quote(schema)} CASCADE`);await admin.end();});
 const version=(await c.query('SHOW server_version')).rows[0].server_version;assert.match(version,/^18\./);t.diagnostic(`Actual PostgreSQL ${version}; synthetic isolated schema; independent runner.`);
 const migrations=readMigrations();await migrate(c,migrations.slice(0,2));await migrate(c);assert.deepEqual(await migrate(c),[]);
 let now=Date.now();const service=new ProfileService(repo,()=>now);
 const a={accountId:randomUUID(),login:'qa_'+randomUUID().slice(0,8),passwordHash:await hashPassword('independent-synthetic-access-only')};
 const b={accountId:randomUUID(),login:'qa_'+randomUUID().slice(0,8),passwordHash:await hashPassword('independent-synthetic-access-only')};await repo.provision([a,b]);
 const clientId=randomUUID(),otherClient=randomUUID();
 const seed=async({gold='500000',steel=10,ember=10,core=2,mode='shop',consumables=0,simulation=null}={})=>repo.transaction(a.accountId,tx=>{
  tx.profile.goldMilli=gold;tx.profile.components={steel,ember,core};tx.profile.consumables={slow_dust:consumables,collector_vial:consumables};tx.profile.loadouts.pudge.quick=['slow_dust','collector_vial'];
  const runId=randomUUID(),sim=simulation||new RunSimulation(runId,71,{config:{spawning:false}});if(!simulation){sim.state.shopCandidates.push({id:'qa-shop',x:0,z:0,at:0});if(mode==='shop')assert.ok(sim.enterShop('qa-shop'));else if(mode==='paused')sim.pause();}
  tx.run={runId:sim.state.runId,snapshot:sim.exportSnapshot(),ownerClientId:clientId,ownerEpoch:1,updatedAt:new Date(now).toISOString(),wallAnchorMs:now-10000,simAnchorTime:sim.state.time,rewardedEnemyIds:[],statsCommitted:false};
 });
 let recoveryOp;
 await t.test('N01 repeat provision retains exact decimal typed wallet and one profile',async()=>{await seed({gold:'9007199254740993'});const before=await repo.getProfile(a.accountId);await repo.provision([a]);assert.deepEqual(await repo.getProfile(a.accountId),before);const counts=await c.query("SELECT t.code,count(*)::int n FROM entities e JOIN entity_types t ON t.id=e.entity_type_id WHERE t.code IN ('account','profile','loadout') GROUP BY t.code ORDER BY t.code");assert.deepEqual(counts.rows.map(x=>[x.code,x.n]),[['account',2],['loadout',2],['profile',2]]);const money=await c.query("SELECT v.data_type,v.value_decimal FROM entity_parameter_values v JOIN entity_parameters p ON p.id=v.parameter_id WHERE p.code='gold-milli' AND v.value_decimal='9007199254740993'");assert.equal(money.rows[0].data_type,'decimal');t.diagnostic('typed gold >2^53 preserved exactly');});
 await t.test('A19 missing one cost changes nothing, including journal',async()=>{await seed({steel:1});const before=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId),operation=op(before,clientId,'craft',{definitionId:'fast_reel'});await assert.rejects(service.perform(a.accountId,operation),failure('INSUFFICIENT_RESOURCES'));assert.deepEqual(await repo.getProfile(a.accountId),before);assert.deepEqual(await repo.getRun(a.accountId),run);assert.equal(await repo.getOperation(a.accountId,operation.operationId),null);});
 await t.test('A20 same id one item/debit; changed payload and stale revision denied',async()=>{await seed();const before=await repo.getProfile(a.accountId),operation=op(before,clientId,'craft',{definitionId:'fast_reel'});const first=await service.perform(a.accountId,operation),again=await service.perform(a.accountId,operation);assert.equal(first.profile.goldMilli,(BigInt(before.goldMilli)-100000n).toString());assert.equal(first.profile.components.steel,before.components.steel-2);assert.equal(first.profile.items.length,before.items.length+1);assert.equal(again.replayed,true);assert.deepEqual(again.profile,first.profile);await assert.rejects(service.perform(a.accountId,{...operation,payload:{definitionId:'long_link'}}),failure('OPERATION_CONFLICT'));await assert.rejects(service.perform(a.accountId,op(before,clientId,'craft',{definitionId:'fast_reel'})),failure('REVISION_CONFLICT'));recoveryOp=operation;});
 await t.test('A32 actual SQL failure after property writes rolls back wallet/item/run/journal',async()=>{await seed();const before=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId),operation=op(before,clientId,'craft',{definitionId:'fast_reel'});await c.query(`CREATE FUNCTION independent_break_commit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.operation_id='${operation.operationId}'::uuid THEN RAISE EXCEPTION 'independent failure after domain write'; END IF; RETURN NEW; END $$`);await c.query('CREATE TRIGGER independent_break_commit BEFORE INSERT ON profile_operations FOR EACH ROW EXECUTE FUNCTION independent_break_commit()');try{await assert.rejects(service.perform(a.accountId,operation),failure('PROFILE_STORAGE_UNAVAILABLE'));assert.deepEqual(await repo.getProfile(a.accountId),before);assert.deepEqual(await repo.getRun(a.accountId),run);assert.equal(await repo.getOperation(a.accountId,operation.operationId),null);}finally{await c.query('DROP TRIGGER independent_break_commit ON profile_operations');await c.query('DROP FUNCTION independent_break_commit()');}});
 await t.test('N05 controlled overlap gives one writer and one stale rejection',async()=>{await seed({gold:'100000',steel:2});const before=await repo.getProfile(a.accountId);let entered,release;const gate=new Promise(r=>release=r),barrier=new Promise(r=>entered=r);let held=false;const blocked=new Proxy(repo,{get(target,key){if(key==='transaction')return(id,fn)=>target.transaction(id,async tx=>{const result=await fn(tx);if(!held){held=true;entered();await gate;}return result;});const v=target[key];return typeof v==='function'?v.bind(target):v;}});const first=new ProfileService(blocked,()=>now).perform(a.accountId,op(before,clientId,'craft',{definitionId:'fast_reel'}));await barrier;const second=service.perform(a.accountId,op(before,clientId,'craft',{definitionId:'fast_reel'}));release();const settled=await Promise.allSettled([first,second]);assert.equal(settled[0].status,'fulfilled');assert.equal(settled[1].status,'rejected');assert.equal(settled[1].reason.code,'REVISION_CONFLICT');const after=await repo.getProfile(a.accountId);assert.equal(after.goldMilli,'0');assert.equal(after.components.steel,0);assert.equal(after.items.length,before.items.length+1);});
 await t.test('N03 owner controls property and takeover invalidates old client',async()=>{await seed();const before=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId);for(const [type,payload]of [['craft',{definitionId:'fast_reel'}],['equip',{slot:'weapon',itemId:null}],['quick_slots',{slots:[null,null]}]])await assert.rejects(service.perform(a.accountId,op(before,otherClient,type,payload)),failure('RUN_NOT_OWNER'));const takeover=await service.perform(a.accountId,op(before,otherClient,'takeover_run',{runId:run.runId}));assert.equal(takeover.run.ownerEpoch,2);assert.equal(takeover.run.snapshot.state.phase,'shop');await assert.rejects(service.perform(a.accountId,op(takeover.profile,clientId,'pause_run',{runId:run.runId,ownerEpoch:1})),failure('RUN_NOT_OWNER'));const foreign=await repo.getProfile(b.accountId);await assert.rejects(service.perform(b.accountId,op(foreign,clientId,'takeover_run',{runId:run.runId})),failure('RUN_NOT_FOUND'));assert.equal(await repo.getOperation(b.accountId,recoveryOp.operationId),null);});
 await t.test('A24 server replay kill before terminal bullet keeps reward once',async()=>{const sim=new RunSimulation(randomUUID(),9,{config:{spawning:false},initialEnemies:[{id:'reward-target',x:0,z:.9}],initialProjectiles:[{id:'terminal',sourceEnemyId:'other',x:0,z:.55,velocity:{x:0,z:-8},radius:.12,lifetimeRemaining:8}]});await seed({gold:'0',steel:0,ember:0,core:0,simulation:sim});const before=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId),operation=op(before,clientId,'advance_run',{runId:run.runId,ownerEpoch:1,frames:[[{type:'cast',aim:{x:0,z:20}}]]});const result=await service.perform(a.accountId,operation);assert.equal(result.run.snapshot.state.phase,'gameOver');assert.equal(result.profile.goldMilli,'5000');assert.equal(result.run.loot.goldMilli,'5000');assert.deepEqual(result.run.loot.components,{steel:0,ember:0,core:0});assert.equal(result.profile.stats.totalKills,before.stats.totalKills+1);assert.equal(result.profile.stats.runs,before.stats.runs+1);assert.ok((await repo.getRun(a.accountId)).rewardedEnemyIds.includes('reward-target'));const repeated=await service.perform(a.accountId,operation);assert.deepEqual(repeated.profile,result.profile);assert.equal(repeated.replayed,true);let latest=result.profile;for(let i=0;i<2;i++){const end=await service.perform(a.accountId,op(latest,clientId,'end_run',{runId:run.runId,ownerEpoch:1}));assert.equal(end.profile.stats.runs,result.profile.stats.runs);latest=end.profile;}recoveryOp=operation;});
 await t.test('A22 consume 3→2 then death/reopen; rejected duplicate adds no spend',async()=>{await seed({mode:'running',consumables:3});const before=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId),operation=op(before,clientId,'consume',{runId:run.runId,ownerEpoch:1,definitionId:'collector_vial'});const used=await service.perform(a.accountId,operation);assert.equal(used.profile.consumables.collector_vial,2);assert.equal((await service.perform(a.accountId,operation)).profile.consumables.collector_vial,2);await assert.rejects(service.perform(a.accountId,op(used.profile,clientId,'consume',{runId:run.runId,ownerEpoch:1,definitionId:'collector_vial'})),failure('CONSUMABLE_UNAVAILABLE'));assert.equal((await repo.getProfile(a.accountId)).revision,used.profile.revision);const end=await service.perform(a.accountId,op(used.profile,clientId,'end_run',{runId:run.runId,ownerEpoch:1}));assert.equal(end.profile.consumables.collector_vial,2);assert.equal(end.run.snapshot.state.effects.collectorKillsRemaining,0);const reopened=new PgRepository(pool);assert.deepEqual(await reopened.getProfile(a.accountId),end.profile);assert.deepEqual(await reopened.getRun(a.accountId),await repo.getRun(a.accountId));});
 await t.test('O11 real pg_dump/restore preserves profile, operation replay, snapshot and owner',async()=>{const profile=await repo.getProfile(a.accountId),run=await repo.getRun(a.accountId),saved=await repo.getOperation(a.accountId,recoveryOp.operationId);const bytes=await dumpRestore(schema,admin);assert.deepEqual(await repo.getProfile(a.accountId),profile);assert.deepEqual(await repo.getRun(a.accountId),run);assert.deepEqual(await repo.getOperation(a.accountId,recoveryOp.operationId),saved);assert.equal((await service.perform(a.accountId,recoveryOp)).replayed,true);assert.deepEqual(await repo.getProfile(a.accountId),profile);t.diagnostic(`Actual PostgreSQL custom dump restored ${bytes} bytes.`);});
});
