import {createHash} from 'node:crypto';
import {BALANCE_PARAMETERS,LEGACY_BALANCE_PARAMETERS,DEFAULT_BALANCE_VALUES,BALANCE_TYPE_ID,BALANCE_POINTER_ID,parameterCode} from '../balance/model.js';
export const FORGE_TYPE_ID='ca5f0000-0000-5000-a000-000000000001';
export const FORGE_INITIAL_REVISION='ca5f0000-0000-5000-a000-000000000002';
const q=(v:string)=>`'${v.replaceAll("'","''")}'`;
const id=(s:string)=>createHash('md5').update(s).digest('hex').replace(/^(........)(....)(....)(....)(............)$/,'$1-$2-$3-$4-$5');
export const FORGE_PARAMETERS=['owner','apprentice','smelter','press','alchemy','tap-level','organization-level','settled-at-ms','fraction-millionths'];
export function forgeSeedSql():string{
 const extra=BALANCE_PARAMETERS.filter(p=>!LEGACY_BALANCE_PARAMETERS.some(l=>l.key===p.key));
 const lines=[`-- R5 additive migration. Existing wallet, item inventory, receipts and run pins are preserved.`,
 `SELECT set_config('foxy.forge_writer','runner-forge.1',true);`,
 `ALTER TABLE entity_parameters DISABLE TRIGGER balance_protect_history;`,
 `UPDATE entity_parameters SET text_pattern='^runner-balance[.][12]$' WHERE entity_type_id=${q(BALANCE_TYPE_ID)} AND code='schema-version';`];
 lines.push(`INSERT INTO entity_parameters(id,entity_type_id,code,label,data_type,is_required,is_unique,integer_min,integer_max) VALUES(${q(id('runner-forge.1:publication-order'))},${q(BALANCE_TYPE_ID)},'publication-order','Publication order','integer',false,true,1,9007199254740991);`);
 for(const p of extra){const type=p.type==='integer'?'integer':'decimal',min=p.type==='goldMilli'?'0':String(p.min),max=p.type==='goldMilli'?'9223372036854775807':String(p.max);lines.push(`INSERT INTO entity_parameters(id,entity_type_id,code,label,data_type,is_required,integer_min,integer_max,decimal_min,decimal_max) VALUES(${q(id('runner-balance.1:'+p.key))},${q(BALANCE_TYPE_ID)},${q(parameterCode(p.key))},${q(p.group+' · '+p.label)},${q(type)},false,${type==='integer'?min:'NULL'},${type==='integer'?max:'NULL'},${type==='decimal'?min:'NULL'},${type==='decimal'?max:'NULL'});`);}
 lines.push(`SET CONSTRAINTS ALL IMMEDIATE;`, `ALTER TABLE entity_parameters ENABLE TRIGGER balance_protect_history;`, `SET CONSTRAINTS ALL DEFERRED;`,
 `UPDATE entity_parameters SET text_pattern='^(fast_reel|long_link|piercing_tooth|return_sickle|conductor_cuffs|side_step_boots|trophy_counter|debt_clock)$' WHERE entity_type_id='ca5d0000-0000-5000-a000-000000000003' AND code='definition';`,
 `INSERT INTO entity_types(id,code) VALUES(${q(FORGE_TYPE_ID)},'workshop');`);
 for(const code of FORGE_PARAMETERS){if(code==='owner')lines.push(`INSERT INTO entity_parameters(id,entity_type_id,code,label,data_type,is_required,is_unique,reference_type_id) VALUES(${q(id('runner-forge.1:'+code))},${q(FORGE_TYPE_ID)},'owner','Owner','reference',true,true,'ca5d0000-0000-5000-a000-000000000001');`);else lines.push(`INSERT INTO entity_parameters(id,entity_type_id,code,label,data_type,is_required,integer_min,integer_max) VALUES(${q(id('runner-forge.1:'+code))},${q(FORGE_TYPE_ID)},${q(code)},${q(code)},'integer',true,0,${code==='fraction-millionths'?999999:code.endsWith('-level')?3:9007199254740991});`);}
 lines.push(`INSERT INTO entities(id,entity_type_id) VALUES(${q(FORGE_INITIAL_REVISION)},${q(BALANCE_TYPE_ID)});`,
 `INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,position,value_text,value_integer,value_decimal,value_boolean,value_timestamp,value_reference,reference_type_id) SELECT ${q(FORGE_INITIAL_REVISION)},v.parameter_id,v.entity_type_id,v.data_type,v.is_multiple,v.is_unique,v.position,v.value_text,v.value_integer,v.value_decimal,v.value_boolean,v.value_timestamp,v.value_reference,v.reference_type_id FROM entity_parameter_values v JOIN entity_parameter_values a ON a.value_reference=v.entity_id AND a.entity_id=${q(BALANCE_POINTER_ID)} WHERE v.parameter_id NOT IN(SELECT id FROM entity_parameters WHERE entity_type_id=${q(BALANCE_TYPE_ID)} AND code IN('schema-version','published-at','published-by','publication-order'));`);
 for(const p of extra)lines.push(`INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_${p.type==='integer'?'integer':'decimal'}) VALUES(${q(FORGE_INITIAL_REVISION)},${q(id('runner-balance.1:'+p.key))},${q(BALANCE_TYPE_ID)},${q(p.type==='integer'?'integer':'decimal')},false,false,${String(DEFAULT_BALANCE_VALUES[p.key])});`);
 lines.push(`INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_text) SELECT ${q(FORGE_INITIAL_REVISION)},id,entity_type_id,'text',false,false,'runner-balance.2' FROM entity_parameters WHERE entity_type_id=${q(BALANCE_TYPE_ID)} AND code='schema-version';`,
 `INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_timestamp) SELECT ${q(FORGE_INITIAL_REVISION)},id,entity_type_id,'timestamp',false,false,date_trunc('milliseconds',clock_timestamp()) FROM entity_parameters WHERE entity_type_id=${q(BALANCE_TYPE_ID)} AND code='published-at';`,
 `INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_integer) SELECT ${q(FORGE_INITIAL_REVISION)},id,entity_type_id,'integer',false,true,1 FROM entity_parameters WHERE entity_type_id=${q(BALANCE_TYPE_ID)} AND code='publication-order';`,
 `UPDATE entities SET state='active',revision=1 WHERE id=${q(FORGE_INITIAL_REVISION)};`,
 `UPDATE entity_parameter_values SET value_reference=${q(FORGE_INITIAL_REVISION)} WHERE entity_id=${q(BALANCE_POINTER_ID)};`,
 `DO $$ DECLARE a record;obj uuid;stamp bigint; BEGIN SELECT (extract(epoch FROM value_timestamp)*1000)::bigint INTO stamp FROM entity_parameter_values v JOIN entity_parameters p ON p.id=v.parameter_id WHERE v.entity_id=${q(FORGE_INITIAL_REVISION)} AND p.code='published-at'; FOR a IN SELECT id FROM entities WHERE entity_type_id='ca5d0000-0000-5000-a000-000000000001' AND state='active' LOOP obj:=md5('runner-forge.1:account:'||a.id::text)::uuid; INSERT INTO entities(id,entity_type_id) VALUES(obj,${q(FORGE_TYPE_ID)}); INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_reference,reference_type_id) VALUES(obj,${q(id('runner-forge.1:owner'))},${q(FORGE_TYPE_ID)},'reference',false,true,a.id,'ca5d0000-0000-5000-a000-000000000001'); INSERT INTO entity_parameter_values(entity_id,parameter_id,entity_type_id,data_type,is_multiple,is_unique,value_integer) SELECT obj,id,entity_type_id,'integer',false,false,CASE WHEN code='settled-at-ms' THEN stamp ELSE 0 END FROM entity_parameters WHERE entity_type_id=${q(FORGE_TYPE_ID)} AND code<>'owner'; UPDATE entities SET state='active',revision=1 WHERE id=obj; END LOOP; END $$;`,
 `CREATE FUNCTION forge_fence_writer() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE typ uuid; BEGIN IF TG_TABLE_NAME='profile_runs' THEN typ:='ca5d0000-0000-5000-a000-000000000002'; ELSE IF TG_OP='DELETE' THEN typ:=OLD.entity_type_id; ELSE typ:=NEW.entity_type_id; END IF; END IF; IF typ IN('ca5d0000-0000-5000-a000-000000000002','ca5d0000-0000-5000-a000-000000000003','ca5d0000-0000-5000-a000-000000000004',${q(FORGE_TYPE_ID)},${q(BALANCE_TYPE_ID)},'ca5b0000-0000-5000-a000-000000000003') AND current_setting('foxy.forge_writer',true) IS DISTINCT FROM 'runner-forge.1' THEN RAISE EXCEPTION 'R5 compatible wallet writer required' USING ERRCODE='23514'; END IF; RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END $$;`,
 `CREATE TRIGGER forge_fence_writer BEFORE INSERT OR UPDATE OR DELETE ON entities FOR EACH ROW EXECUTE FUNCTION forge_fence_writer();`,
 `CREATE TRIGGER forge_fence_writer BEFORE INSERT OR UPDATE OR DELETE ON entity_parameter_values FOR EACH ROW EXECUTE FUNCTION forge_fence_writer();`,
 `CREATE TRIGGER forge_fence_writer BEFORE INSERT OR UPDATE OR DELETE ON profile_runs FOR EACH ROW EXECUTE FUNCTION forge_fence_writer();`,
 `CREATE FUNCTION forge_validate_balance() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE obj uuid;schema text; BEGIN IF TG_TABLE_NAME='entities' THEN IF TG_OP='DELETE' THEN obj:=OLD.id; ELSE obj:=NEW.id; END IF; ELSE IF TG_OP='DELETE' THEN obj:=OLD.entity_id; ELSE obj:=NEW.entity_id; END IF; END IF; IF EXISTS(SELECT 1 FROM entities WHERE id=obj AND entity_type_id=${q(BALANCE_TYPE_ID)} AND state='active') THEN SELECT value_text INTO schema FROM entity_parameter_values v JOIN entity_parameters p ON p.id=v.parameter_id WHERE v.entity_id=obj AND p.code='schema-version'; IF schema='runner-balance.2' THEN IF EXISTS(SELECT 1 FROM entity_parameters p WHERE p.entity_type_id=${q(BALANCE_TYPE_ID)} AND p.code IN('publication-order',${extra.map(p=>q(parameterCode(p.key))).join(',')}) AND NOT EXISTS(SELECT 1 FROM entity_parameter_values v WHERE v.entity_id=obj AND v.parameter_id=p.id)) THEN RAISE EXCEPTION 'R5 balance is incomplete' USING ERRCODE='23514'; END IF; IF EXISTS(SELECT 1 FROM entity_parameter_values v JOIN entity_parameters p ON p.id=v.parameter_id WHERE v.entity_id=obj AND p.code IN(${extra.filter(p=>p.type==='goldMilli').map(p=>q(parameterCode(p.key))).join(',')}) AND v.value_decimal<>trunc(v.value_decimal)) THEN RAISE EXCEPTION 'R5 money and rates must be exact integers' USING ERRCODE='23514'; END IF; IF ${extra.filter(p=>p.key.endsWith('baseCostGoldMilli')).map(p=>`mod(balance_number(obj,${q(p.key)}),1000)<>0`).join(' OR ')} THEN RAISE EXCEPTION 'Production base prices require whole gold' USING ERRCODE='23514'; END IF; END IF; ELSIF obj=${q(BALANCE_POINTER_ID)} THEN IF NOT EXISTS(SELECT 1 FROM entity_parameter_values a JOIN entity_parameter_values s ON s.entity_id=a.value_reference JOIN entity_parameters p ON p.id=s.parameter_id WHERE a.entity_id=obj AND p.code='schema-version' AND s.value_text='runner-balance.2') THEN RAISE EXCEPTION 'Current balance requires R5 schema' USING ERRCODE='23514'; END IF; END IF; RETURN NULL; END $$;`,
 `CREATE CONSTRAINT TRIGGER forge_validate_balance AFTER INSERT OR UPDATE OR DELETE ON entities DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION forge_validate_balance();`,
 `CREATE CONSTRAINT TRIGGER forge_validate_balance AFTER INSERT OR UPDATE OR DELETE ON entity_parameter_values DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION forge_validate_balance();`,
 `CREATE FUNCTION forge_protect_metadata() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE typ uuid; BEGIN IF TG_TABLE_NAME='entity_types' THEN typ:=OLD.id; ELSE IF TG_OP='DELETE' THEN typ:=OLD.entity_type_id; ELSE typ:=NEW.entity_type_id; END IF; END IF; IF typ=${q(FORGE_TYPE_ID)} AND EXISTS(SELECT 1 FROM entities WHERE entity_type_id=typ AND state='active') THEN RAISE EXCEPTION 'Live workshop metadata is immutable' USING ERRCODE='23514'; END IF; RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END $$;`,
 `CREATE TRIGGER forge_protect_metadata BEFORE INSERT OR UPDATE OR DELETE ON entity_parameters FOR EACH ROW EXECUTE FUNCTION forge_protect_metadata();`,
 `CREATE TRIGGER forge_protect_metadata BEFORE UPDATE OR DELETE ON entity_types FOR EACH ROW EXECUTE FUNCTION forge_protect_metadata();`,
 `REVOKE ALL ON FUNCTION forge_fence_writer(),forge_validate_balance(),forge_protect_metadata() FROM PUBLIC;`);
 return lines.join('\n')+'\n';
}
